first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views


app_name = 'first_app'

urlpatterns = [
    url(r'^first_page/',views.first_page,name='first_page'),
    url(r'^second_page/',views.second_page,name='second_page'),
    url(r'^users_page/',views.users_page,name='users_page'),
    url(r'^forms_page/',views.forms_page,name='forms_page'),
    url(r'^create_users/',views.create_users,name='create_users'),
    url(r'^relative_page/',views.relative_page,name='relative_page'),
    url(r'^register_page/',views.register_page,name='register_page'),
    url(r'^user_login/',views.user_login,name='user_login'),
]

first_project/first_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from first_app import views, urls

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),

]

first_project/first_app/models.py
from django.db import models

# Create your models here.


class topic(models.Model):
    top_name = models.CharField(blank=True, max_length=100,unique=True)


    def __str__(self):
        return self.top_name


class webpage(models.Model):
    topic = models.ForeignKey(topic)
    name = models.CharField(max_length=100,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class accessrecord(models.Model):
    name = models.ForeignKey(webpage)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class db_users(models.Model):
    firstname = models.CharField(blank=True, max_length=100)
    lastname = models.CharField(blank=True, max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return str(self.email)

from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    #additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import db_users


# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("Name needs to start with z")


class FormPage(forms.Form):
    # name = forms.CharField(validators=[check_for_z])
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter Your Email Again')
    text = forms.CharField(widget=forms.Textarea)
    # botcatcher = forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Make sure Emails Match!")
    #
    #
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0 :
    #         raise forms.ValidationError("Botchtcher Validation Error!")
    #     return botcatcher

class CreateUser(forms.ModelForm):

    class Meta:
        model = db_users
        fields = '__all__'



from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import topic,webpage,accessrecord,db_users
from first_app.forms import CreateUser

# Create your views here.

def index(request):
    return render(request,'first_app/index.html')

def first_page(request):
    my_dict = {"insert_me":"I am first project"}
    return render(request,'first_app/first_page.html',my_dict)

def second_page(request):
    webpages_list = accessrecord.objects.order_by('date')
    date_dict = {'access_record':webpages_list}
    return render(request,'first_app/second_page.html',context=date_dict)

def users_page(request):
    users_list = db_users.objects.order_by('firstname')
    users_dict = {'users_list':users_list}
    return render(request,'first_app/users_page.html',context=users_dict)

from . import forms


def forms_page(request):
    form = forms.FormPage()
    if request.method == 'POST':
        form = forms.FormPage(request.POST)

        if form.is_valid():
            print("Validation Success!")
            print("NAME :"+ form.cleaned_data['name'])
            print("EMAIL :"+ form.cleaned_data['email'])
            print("TEXT :"+ form.cleaned_data['text'])

    return render(request,'first_app/forms_page.html',{'form':form})

def create_users(request):
    form = CreateUser()
    if request.method == 'POST':
        form = CreateUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return users_page(request)
    return render(request,'first_app/create_users.html',{'form':form})


def relative_page(request):
    return render(request,'first_app/relative_page.html')

from first_app.forms import UserForm, UserProfileInfoForm

def register_page(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form =UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/registration.html',{'user_form':user_form,
                                                         'profile_form':profile_form,
                                                         'registered':registered})

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse('Invalid login details supplied.')
    else:
        return render(request,'first_app/login_page.html',{})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
   <nav class="navbar navbar-default navbar-static-top">
     <div class="container">
       <ul class="nav navbar-nav">
         <li><a class="navbar-brand" href="{% url 'index' %}">Index Page</a></li>
         <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin Page</a></li>
         <li><a class="navbar-link" href="{% url 'first_app:users_page' %}">Users Page</a></li>
         <li><a class="navbar-link" href="{% url 'first_app:create_users' %}">Create User</a></li>
         <li><a class="navbar-link" href="{% url 'first_app:forms_page' %}">Forms Page</a></li>
         <li><a class="navbar-link" href="{% url 'first_app:relative_page' %}">Relative URL Page</a></li>
         <li><a class="navbar-link" href="{% url 'first_app:register_page' %}">Registration Page</a></li>
         {% if user.is_authenticated %}
         <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
         {% else %}
         <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>
         {% endif %}

       </ul>

     </div>

   </nav>

   <div class="container">
     {% block body_block %}

     {% endblock  %}
   </div>


  </body>
</html>

first_project/templates/first_app/create_users.html
{% extends "first_app/base.html" %}
{% block body_block %}
   <h1>Fill out the form</h1>
    <div class="container">
      <form  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
{% endblock  %}

first_project/templates/first_app/first_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "/css/mystyle.css" %}">
  </head>
  <body>
    <h1>This my second page!</h1>
    {{ insert_me }}
    <img src="{% static "images/aboutus.jpg" %}" alt="No img file found in static/images/aboutus.jpg">
  </body>
</html>

first_project/templates/first_app/forms_page.html
{% extends "first_app/base.html" %}
{% block body_block %}

   <h1>Fill out the form</h1>
    <div class="container">
      <form  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>

    </div>
        {% csrf_token %}

{% endblock  %}

first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}

{% block body_block %}
<h1> This is index page! </h1>
<h2> Template Inheritence.</h2>
{% endblock  %}

first_project/templates/first_app/login_page.html
{% extends "first_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>

  <form action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username </label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input class="btn btn-primary" type="submit" name="" value="Login">

  </form>

</div>

{% endblock  %}

first_project/templates/first_app/registration.html
{% extends "first_app/base.html" %}
{% load staticfiles %}


{% block body_block %}
<div class="container">
  <div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="Register">
  </form>

  {% endif %}


  </div>
</div>

{% endblock  %}

first_project/templates/first_app/relative_page.html
{% extends "first_app/base.html" %}
{% block body_block %}

  <div class="container">


  <h1>welcome to relatve url templates.</h1>
  <a href="{% url 'first_app:users_page' %}">The Users Page</a> <br>
  <a href="{% url 'admin:index' %}">The Admin Page</a><br>
  <a href="{% url 'index' %}">The Index Page</a>
  </div>

{% endblock  %}

first_project/templates/first_app/second_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
  </head>
  <body>
      <h1>Hi Wecome to second page!</h1>
      <h2>Here is access record:</h2>

      <div class="djangotwo">

      {% if access_record %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        {% for acc in access_record %}
        <tr>
          <td>{{acc.name}}</td>
          <td>{{acc.date}}</td>
        </tr>

        {% endfor %}

      </table>
      {% else %}
      <p>No Access Records Found!</p>
      {% endif %}
      </div>
  </body>
</html>

first_project/templates/first_app/users_page.html
{% extends "first_app/base.html" %}
{% load my_filters %}
{% load staticfiles %}
{% block  body_block %}

<h1>Find the users!</h1>

    {% if users_list %}
<ol>


    {% for users_rec in users_list %}
    <li> Users Info</li>
    <ul>
      <li>First Name : {{users_rec.firstname|upper|add:'99'|cut_string:'99'}}</li>
      <li>Last Name  : {{users_rec.lastname|lower}}</li>
      <li>Email      : {{users_rec.email}}</li>
    </ul>

    {% endfor %}

    {% else %}
    <P>
      No Users Exist!
    </P>

</ol>
    {% endif %}


{% endblock  %}